name: Download and release devstats data bundle

on: push
  # schedule:
  #   - cron: "0 1 * * 0"  # 01:00 on Sundays, https://crontab.guru/#0_1_*_*_0

jobs:
  devstats-release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: stefanv/devstats-query-action@main
        with:
          repos: |
            - scientific-python/spin
            - scientific-python/lazy-loader
            # - numpy/numpy
            # - scipy/scipy
            # - matplotlib/matplotlib
            # - pandas-dev/pandas
            # - scikit-learn/scikit-learn
            # - scikit-image/scikit-image
            # - networkx/networkx
            # - astropy/astropy
            # - sunpy/sunpy
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: devstats-scientific-python

      - uses: actions/download-artifact@v4
        with:
          name: devstats-scientific-python

      - uses: actions/checkout@v4
        with:
          repository: scientific-python/devstats
          path: devstats

      - name: Set variables
        shell: bash
        run: |
          ISODATE=$(date +"%Y-%m-%d")
          echo "ISODATE=$ISODATE" >> $GITHUB_ENV

      - name: Bundle queries
        shell: bash
        run: |
          FILENAME=$ISODATE-devstats-queries.xz
          tar cfJ queries.xz devstats/devstats/queries/*

      - name: List all files
        shell: bash
        run: |
          ls -R

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.RELEASE_TOKEN }}  # Needs to have Contents: read and write permission
          files: |
            *.xz
