name: Download and release devstats data bundle

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * 0"  # 01:00 on Sundays, https://crontab.guru/#0_1_*_*_0

jobs:
  devstats-release:
    runs-on: ubuntu-latest
    steps:
      - uses: stefanv/devstats-query-action@main
        with:
          repos: |
            - numpy/numpy
            - scipy/scipy
            - matplotlib/matplotlib
            - pandas-dev/pandas
            - scikit-learn/scikit-learn
            - scikit-image/scikit-image
            - networkx/networkx
            - astropy/astropy
            - sunpy/sunpy
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: devstats-scientific-python

      - uses: actions/download-artifact@v4
        with:
          name: devstats-scientific-python

      - name: Unpack artifact
        shell: bash
        run: unzip devstats-scientific-python.zip

      - uses: actions/checkout@v4
        with:
          repository: scientific-python/devstats

      - name: Set variables
        shell: bash
        run: |
          ISODATE=$(date +"%Y-%m-%d")
          echo "ISODATE=$ISODATE" >> $GITHUB_ENV

      - name: Bundle queries
        shell: bash
        run: |
          FILENAME="$ISODATE-devstats-queries.xz"
          tar cfJ queries.xz devstats/devstats/queries/*

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        name: ${{ env.DATE }}
        files: |
          *.xz
